disabled_plugins = ["cri"]
root = "/var/lib/containerd"
state = "/run/containerd"

[grpc]
  address = "/run/containerd/containerd.sock"

[debug]
  address = "/run/containerd/debug.sock"
  level = "debug"

[plugins]
  [plugins."io.containerd.runtime.v1.linux"]
    runtime = "runc"
    shim = "containerd-shim"
