disabled_plugins = ["cri", "aufs", "btrfs", "zfs"]
root = "/var/lib/containerd"
state = "/run/containerd"

[grpc]
  address = "/run/containerd/containerd.sock"

[debug]
  address = "/run/containerd/debug.sock"
  level = "debug"
